"""
Async AI task planner — converts natural language commands into structured TaskPlan objects.

The planner combines a :class:`ModelManager` (for AI completions) with a
:class:`ContextManager` (for sliding-window conversation history) to provide
stateful, multi-turn planning.  A :class:`ResponseParser` turns the raw AI
output into validated Pydantic :class:`TaskPlan` objects.
"""

from __future__ import annotations

import logging
from collections.abc import AsyncIterator

from .context_manager import ContextManager
from .model_manager import ModelManager
from .response_parser import ResponseParser, TaskPlan, parse_task_plan

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# System prompt
# ---------------------------------------------------------------------------

SYSTEM_PROMPT = """You are OmniAutomator's task planning AI. Convert user commands into structured JSON task plans.

Always respond with valid JSON matching this schema:
{
  "goal": "brief description of what will be accomplished",
  "estimated_duration": "e.g. 30 seconds",
  "steps": [
    {
      "action": "action_name",
      "category": "filesystem|system|web|code|devops|gui|data|security",
      "params": {"param_key": "param_value"},
      "description": "what this step does",
      "required": true,
      "priority": 0
    }
  ],
  "context": {}
}

Keep action names lowercase with underscores. Map user intent to the most specific action available."""


# ---------------------------------------------------------------------------
# TaskPlanner
# ---------------------------------------------------------------------------


class TaskPlanner:
    """
    Async AI task planner.

    Converts natural-language automation commands into structured
    :class:`~response_parser.TaskPlan` objects by querying the AI via
    :class:`~model_manager.ModelManager` and parsing the response with
    :class:`~response_parser.ResponseParser`.

    The planner is stateful: each ``plan()`` / ``plan_with_stream()`` call
    appends the exchange to the :class:`~context_manager.ContextManager` so
    subsequent commands can refer back to earlier ones.

    Parameters
    ----------
    model_manager:
        The :class:`ModelManager` used to execute AI completions.
    context_manager:
        The :class:`ContextManager` that maintains the sliding-window
        conversation history.

    Example::

        mm = ModelManager()
        ctx = ContextManager(max_tokens=8000)
        planner = TaskPlanner(mm, ctx)
        plan = await planner.plan("create a folder named 'my_project'")
        for step in plan.execution_steps:
            print(step.action, step.params)
    """

    def __init__(
        self,
        model_manager: ModelManager,
        context_manager: ContextManager,
    ) -> None:
        self._mm = model_manager
        self._ctx = context_manager
        self._parser = ResponseParser()
        self._extra_system_context: str = ""

        # Set the planning system prompt as the context window's system message.
        self._ctx.set_system_prompt(self._effective_system_prompt())

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    async def plan(self, command: str) -> TaskPlan:
        """
        Generate a :class:`~response_parser.TaskPlan` from a natural language command.

        The exchange (user command + AI response) is recorded in the context
        window so that follow-up calls can reference earlier steps.

        Parameters
        ----------
        command:
            Natural language automation instruction from the user.

        Returns
        -------
        :class:`~response_parser.TaskPlan`
            A validated task plan.  If the AI returns malformed JSON the
            parser falls back to an empty plan rather than raising.
        """
        # Add the command to the context window.
        self._ctx.add_message("user", command)
        messages = self._ctx.get_messages()

        try:
            content, model_used = await self._mm.complete(messages)
            logger.debug("Plan generated by model=%r, len=%d chars", model_used, len(content))
        except Exception as exc:
            logger.error("ModelManager.complete() failed: %s", exc)
            content = "{}"

        # Record the AI's response in the context window.
        self._ctx.add_message("assistant", content)

        # Parse the response into a TaskPlan.
        plan = parse_task_plan(content, original_request=command)
        return plan

    async def plan_with_stream(self, command: str) -> AsyncIterator[str]:
        """
        Stream the planning response token by token for real-time display.

        The full response is accumulated and stored in the context window after
        streaming completes so subsequent ``plan()`` calls have full history.

        Parameters
        ----------
        command:
            Natural language automation instruction from the user.

        Yields
        ------
        str
            Incremental text tokens as they arrive from the model.
        """
        self._ctx.add_message("user", command)
        messages = self._ctx.get_messages()

        accumulated: list[str] = []
        try:
            async for chunk in self._mm.stream(messages):
                if chunk.content:
                    accumulated.append(chunk.content)
                    yield chunk.content
        except Exception as exc:
            logger.error("Streaming failed during plan_with_stream: %s", exc)
            error_msg = f"\n[Streaming error: {exc}]"
            accumulated.append(error_msg)
            yield error_msg
        finally:
            full_response = "".join(accumulated)
            if full_response:
                self._ctx.add_message("assistant", full_response)

    def set_system_context(self, context: str) -> None:
        """
        Inject additional system context (e.g. current directory, OS info).

        The extra context is appended to the base planning system prompt and
        the context window's system message is updated immediately.  Existing
        conversation history is preserved.

        Parameters
        ----------
        context:
            Free-form text to append to the system prompt.

        Example::

            planner.set_system_context(
                "Current directory: /home/user/projects\\nOS: Arch Linux"
            )
        """
        self._extra_system_context = context.strip()
        self._ctx.set_system_prompt(self._effective_system_prompt())

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _effective_system_prompt(self) -> str:
        """Return the full system prompt including any extra context."""
        if self._extra_system_context:
            return f"{SYSTEM_PROMPT}\n\n{self._extra_system_context}"
        return SYSTEM_PROMPT


# ---------------------------------------------------------------------------
# Legacy compatibility shim
# ---------------------------------------------------------------------------
# Code written against the old synchronous AIPoweredTaskPlanner is preserved
# here so existing callers continue to import successfully.
# ---------------------------------------------------------------------------

import os  # noqa: E402
from datetime import datetime  # noqa: E402

from ..utils.logger import get_logger as _get_logger  # noqa: E402
from .openrouter_integration import AITaskPlan, OpenRouterAutomationAI  # noqa: E402


class AIPoweredTaskPlanner:
    """
    Legacy synchronous task planner.

    Deprecated — new code should use :class:`TaskPlanner` with an async
    workflow.  This class is kept so that existing entry points and tests
    that call ``get_ai_task_planner()`` continue to work.
    """

    def __init__(self) -> None:
        self.logger = _get_logger("AIPoweredTaskPlanner")
        self.openrouter_ai: OpenRouterAutomationAI | None = None
        self.task_history: list[dict] = []
        self._initialize_openrouter()

    def _initialize_openrouter(self) -> None:
        try:
            api_key = os.getenv("OPENROUTER_API_KEY")
            if api_key:
                self.openrouter_ai = OpenRouterAutomationAI(api_key=api_key)
                if self.openrouter_ai.is_available:
                    self.logger.info("OpenRouter AI initialised")
                else:
                    self.logger.warning("OpenRouter AI not available")
        except Exception as exc:
            self.logger.warning("Failed to initialise OpenRouter: %s", exc)

    def plan_and_execute(self, request: str, context: dict | None = None) -> dict:
        """Generate a task plan and execute it (legacy sync API)."""
        from .task_executor import get_ai_task_executor

        self.logger.info("Processing request: %s", request)
        task_plan = self._generate_task_plan(request, context)
        if not task_plan:
            return {"success": False, "error": "Failed to generate task plan", "request": request}

        executor = get_ai_task_executor()
        unknown_actions: list[str] = []
        try:
            known = set(executor.execution_handlers.keys())
            for step in task_plan.get("execution_steps", []):
                action = (step.get("action") or "").lower()
                if action and action not in known:
                    unknown_actions.append(action)
        except Exception:
            unknown_actions = []

        if unknown_actions:
            self.logger.warning("Unknown actions in plan: %s — using NL fallback.", unknown_actions)
            try:
                result = executor.parse_and_execute_nl(request, confirm=False)
                result["note"] = (
                    "NL fallback executed in dry-run mode. "
                    "Re-run in interactive mode to confirm execution."
                )
            except Exception as exc:
                result = {"success": False, "error": f"NL fallback failed: {exc}"}
        else:
            result = executor.execute_task_plan(task_plan)

        self.task_history.append(
            {
                "request": request,
                "task_plan": task_plan,
                "execution_result": result,
                "timestamp": datetime.now().isoformat(),
            }
        )
        return result

    def _generate_task_plan(self, request: str, context: dict | None = None) -> dict | None:
        if self.openrouter_ai and self.openrouter_ai.is_available:
            try:
                ai_plan: AITaskPlan = self.openrouter_ai.analyze_automation_request(
                    request, context or {}
                )
                if ai_plan and hasattr(ai_plan, "__dict__"):
                    return {
                        "original_request": ai_plan.original_request,
                        "interpreted_intent": ai_plan.interpreted_intent,
                        "confidence_score": ai_plan.confidence_score,
                        "execution_steps": ai_plan.execution_steps,
                        "risk_assessment": ai_plan.risk_assessment,
                        "optimization_suggestions": ai_plan.optimization_suggestions,
                    }
            except Exception as exc:
                self.logger.error("OpenRouter plan generation failed: %s", exc)
        self.logger.warning("Using fallback task plan generation")
        return self._fallback_plan(request)

    @staticmethod
    def _fallback_plan(request: str) -> dict:
        request_lower = request.lower()
        if any(w in request_lower for w in ["ml", "machine learning", "pipeline", "deep learning"]):
            action, description = "create_ml_pipeline", "Create ML pipeline folder structure"
        elif any(w in request_lower for w in ["web app", "website", "frontend", "react", "vue"]):
            action, description = "create_web_app", "Create web app folder structure"
        else:
            action, description = "setup_project", "Create project folder structure"
        return {
            "original_request": request,
            "interpreted_intent": f"Process request: {request}",
            "confidence_score": 0.50,
            "execution_steps": [
                {
                    "action": action,
                    "parameters": {
                        "project_name": "automation_task",
                        "location": os.path.expanduser("~"),
                    },
                    "description": description,
                    "required": True,
                }
            ],
            "risk_assessment": {"risk_level": "low", "concerns": [], "mitigations": []},
            "optimization_suggestions": [],
        }

    def get_task_history(self, limit: int = 10) -> list[dict]:
        return self.task_history[-limit:]

    def switch_ai_model(self, model_name: str) -> bool:
        if not self.openrouter_ai:
            return False
        try:
            self.openrouter_ai.set_model(model_name)
            return True
        except Exception:
            return False


# Process-level singleton for the legacy shim.
_planner_instance: AIPoweredTaskPlanner | None = None


def get_ai_task_planner() -> AIPoweredTaskPlanner:
    """Return the process-wide legacy AIPoweredTaskPlanner singleton."""
    global _planner_instance
    if _planner_instance is None:
        _planner_instance = AIPoweredTaskPlanner()
    return _planner_instance
